# Generated by Django 5.0.6 on 2024-05-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_note_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
    ]
